package:
  name: opencv3
  version: 3.2.0

source:
  fn: opencv-3.2.0.tar.gz
  url: https://github.com/Itseez/opencv/archive/3.2.0.tar.gz
  sha256: b9d62dfffb8130d59d587627703d5f3e6252dce4a94c1955784998da7a39dd35
  
  patches:
    - cap_mpjpeg_decoder.patch  # [win]
    - no_rpath.patch

requirements:
  build:
   - python 2.7*
   - cmake
   - hdf5 1.8.*
   - numpy >=1.10
   - eigen 3.*
   - msinttypes r26  # [win and py<35]

  run:
   - python 2.7*
   - numpy >=1.10
   - hdf5 1.8.*  # [osx]
   - libgcc

test:
  imports:
    - cv2
    - cv2.xfeatures2d

about:
  home: http://opencv.org/
  license: BSD
